const KEY='myEnglishBits_v1',THEME='myEnglishBits_theme';
const sample=[{original:'I everyday jog.',natural:'I go jogging every day.',alternative:'I usually go for a run every day.',meaning:'나는 매일 조깅해.',context:'daily routine',tag:'running'},{original:'In my way, I see cat.',natural:'I saw a cat on my way.',alternative:'I came across a cat while I was out running.',meaning:'가는 길에 고양이를 봤어.',context:'evening jog',tag:'daily life'},{original:"I don't wanna stop my face.",natural:"I don't want to lose my pace.",alternative:"I don't want to break my rhythm.",meaning:'페이스를 잃고 싶지 않아.',context:'jogging',tag:'running'}];
let state=load(),filter='all',pool=[],idx=-1,currentId=null;
function iso(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function pretty(s){if(!s)return'';let[y,m,d]=s.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(y,m-1,d))}
function load(){try{let p=JSON.parse(localStorage.getItem(KEY)||'{"items":[]}');return{items:(p.items||[]).map(x=>({...x,date:x.date||iso(new Date(x.createdAt||Date.now()))}))}}catch{return{items:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function norm(x,date=iso()){return{id:x.id||crypto.randomUUID(),original:String(x.original||'').trim(),natural:String(x.natural||'').trim(),alternative:String(x.alternative||'').trim(),meaning:String(x.meaning||'').trim(),context:String(x.context||'').trim(),tag:String(x.tag||'daily').trim()||'daily',favorite:!!x.favorite,createdAt:x.createdAt||new Date().toISOString(),date:x.date||date}}
function add(arr,date=iso()){let exists=new Set(state.items.map(x=>`${x.date}|${x.natural.toLowerCase()}|${x.meaning.toLowerCase()}`)),fresh=arr.map(x=>norm(x,date)).filter(x=>x.natural&&x.meaning).filter(x=>{let k=`${x.date}|${x.natural.toLowerCase()}|${x.meaning.toLowerCase()}`;if(exists.has(k))return false;exists.add(k);return true});state.items=[...fresh,...state.items];save();return fresh.length}
function speak(text){if(!('speechSynthesis'in window)){alert('이 브라우저에서는 음성 읽기를 지원하지 않아요.');return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.92;speechSynthesis.speak(u)}
function card(item){let n=document.getElementById('cardTpl').content.firstElementChild.cloneNode(true);n.querySelector('.cardTag').textContent=item.tag;n.querySelector('.cardNatural').textContent=item.natural;n.querySelector('.cardMeaning').textContent=item.meaning;n.querySelector('.cardOriginal').textContent=item.original||'—';n.querySelector('.cardAlt').textContent=item.alternative||'—';n.querySelector('.cardContext').textContent=item.context||'';n.querySelector('.cardSpeak').onclick=()=>speak(item.natural);let f=n.querySelector('.fav');f.textContent=item.favorite?'★':'☆';f.onclick=()=>{item.favorite=!item.favorite;save()};n.querySelector('.delete').onclick=()=>{if(confirm('이 표현을 삭제할까요?')){state.items=state.items.filter(x=>x.id!==item.id);save()}};return n}
function renderToday(){let d=iso(),items=state.items.filter(x=>x.date===d);todayLabel.textContent=pretty(d);todayCount.textContent=items.length;todayCards.innerHTML='';if(!items.length)todayCards.innerHTML='<div class="empty">오늘 저장한 표현이 아직 없어요.</div>';else items.forEach(x=>todayCards.appendChild(card(x)))}
function renderLibrary(){let q=searchInput.value.trim().toLowerCase(),items=[...state.items];if(filter==='favorite')items=items.filter(x=>x.favorite);if(q)items=items.filter(x=>[x.original,x.natural,x.alternative,x.meaning,x.context,x.tag,x.date].join(' ').toLowerCase().includes(q));libraryCount.textContent=items.length;libraryList.innerHTML='';if(!items.length){libraryList.innerHTML='<div class="empty">조건에 맞는 표현이 없어요.</div>';return}let groups={};items.forEach(x=>(groups[x.date]??=[]).push(x));Object.keys(groups).sort((a,b)=>b.localeCompare(a)).forEach((d,i)=>{let det=document.createElement('details');det.className='group';det.open=i===0;det.innerHTML=`<summary><strong>${pretty(d)}</strong><span>${groups[d].length} expressions</span></summary>`;let box=document.createElement('div');box.className='groupCards';groups[d].forEach(x=>box.appendChild(card(x)));det.appendChild(box);libraryList.appendChild(det)})}
function fillDates(){let cur=practiceDate.value||'all',dates=[...new Set(state.items.map(x=>x.date))].sort((a,b)=>b.localeCompare(a));practiceDate.innerHTML=`<option value="all">All expressions (${state.items.length})</option>`;dates.forEach(d=>{let o=document.createElement('option');o.value=d;o.textContent=`${pretty(d)} · ${state.items.filter(x=>x.date===d).length} expressions`;practiceDate.appendChild(o)});practiceDate.value=cur==='all'||dates.includes(cur)?cur:'all'}
function selected(){return practiceDate.value==='all'?[...state.items]:state.items.filter(x=>x.date===practiceDate.value)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function resetPractice(){pool=shuffle(selected());idx=pool.length?0:-1;showCurrent()}
function showCurrent(){if(idx<0||!pool.length){currentId=null;pTag.textContent='DAILY';pMeaning.textContent='표현을 저장하면 연습을 시작할 수 있어요.';answer.classList.add('hidden');nextRow.classList.add('hidden');showBtn.classList.remove('hidden');counter.textContent='0 / 0';return}let x=pool[idx];currentId=x.id;pTag.textContent=(x.tag||'daily').toUpperCase();pMeaning.textContent=x.meaning;pNatural.textContent=x.natural;pAlt.textContent=x.alternative?`Also: ${x.alternative}`:'';pOriginal.textContent=x.original||'—';answer.classList.add('hidden');nextRow.classList.add('hidden');showBtn.classList.remove('hidden');counter.textContent=`${idx+1} / ${pool.length}`}
function renderAll(){renderToday();renderLibrary();fillDates();let ids=new Set(selected().map(x=>x.id));if(!pool.length||pool.some(x=>!ids.has(x.id))||pool.length!==ids.size)resetPractice()}
importBtn.onclick=()=>{try{let d=JSON.parse(jsonInput.value);if(!Array.isArray(d))throw 0;let c=add(d);msg.textContent=`${c}개 표현을 오늘 날짜로 추가했어요.`;jsonInput.value=''}catch{msg.textContent='JSON 형식을 확인해 주세요.'}};sampleBtn.onclick=()=>jsonInput.value=JSON.stringify(sample,null,2);manualForm.onsubmit=e=>{e.preventDefault();add([{original:o.value,natural:n.value,alternative:a.value,meaning:m.value,context:c.value,tag:t.value||'daily'}]);manualForm.reset();manualForm.closest('details').open=false};searchInput.oninput=renderLibrary;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderLibrary()});practiceDate.onchange=resetPractice;showBtn.onclick=()=>{if(!pool.length)return;answer.classList.remove('hidden');nextRow.classList.remove('hidden');showBtn.classList.add('hidden')};speakPractice.onclick=()=>{let x=state.items.find(x=>x.id===currentId);if(x)speak(x.natural)};againBtn.onclick=showCurrent;nextBtn.onclick=()=>{if(!pool.length)return;idx++;if(idx>=pool.length){pool=shuffle(selected());idx=0}showCurrent()};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active')});themeBtn.onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem(THEME,document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem(THEME)==='dark')document.body.classList.add('dark');renderAll();
